import type {
  PublishingJob,
  PublishingTimelineEvent,
  PublishingUserSummary,
} from "./types";

const users: Record<string, PublishingUserSummary> = {
  sara: { id: "user-sara", name: "سارا مرادی", initials: "س‌م", role: "کارشناس انتشار" },
  ali: { id: "user-ali", name: "علی احمدی", initials: "ع‌ا", role: "مدیر عملیات" },
  neda: { id: "user-neda", name: "ندا کریمی", initials: "ن‌ک", role: "مدیر محتوا" },
};

function timeline(
  activeStage: PublishingTimelineEvent["stage"],
  activeLabel: string,
  failed = false,
): PublishingTimelineEvent[] {
  const stages: Array<Pick<PublishingTimelineEvent, "stage" | "label">> = [
    { stage: "validation", label: "اعتبارسنجی محتوا" },
    { stage: "media_preparation", label: "آماده‌سازی رسانه" },
    { stage: "upload", label: "بارگذاری رسانه" },
    { stage: "platform_processing", label: "پردازش در پلتفرم" },
    { stage: "publish_request", label: "ارسال برای انتشار" },
    { stage: "verification", label: "راستی‌آزمایی انتشار" },
    { stage: "result_recording", label: "ثبت نتیجه" },
  ];
  const activeIndex = stages.findIndex((item) => item.stage === activeStage);

  return stages.map((item, index) => ({
    id: `${activeStage}-${item.stage}`,
    stage: item.stage,
    label: item.stage === activeStage ? activeLabel : item.label,
    status:
      index < activeIndex
        ? "completed"
        : index === activeIndex
          ? failed
            ? "failed"
            : "active"
          : "pending",
    detail: index === activeIndex ? activeLabel : undefined,
  }));
}

export const publishingFixtures: PublishingJob[] = [
  {
    id: "job-1001",
    contentId: "content-501",
    title: "معرفی محصول جدید تابستانه",
    captionPreview: "در این مجموعه ویژگی‌های نسخه جدید و تجربه استفاده روزمره معرفی می‌شود.",
    contentType: "carousel",
    campaign: { id: "campaign-launch", name: "معرفی نسخه جدید" },
    status: "uploading",
    progress: 65,
    scheduledAt: "2026-06-25T14:30:00+03:30",
    startedAt: "2026-06-25T14:27:00+03:30",
    estimatedCompletionAt: "2026-06-25T14:32:00+03:30",
    retryCount: 0,
    maxRetryCount: 3,
    approvalStatus: "approved",
    responsible: users.sara,
    targets: [
      {
        id: "target-1001-instagram",
        platform: "instagram",
        accountId: "account-instagram-main",
        accountName: "نشرینو",
        accountHandle: "@nashrino_official",
        status: "uploading",
        progress: 65,
      },
    ],
    timeline: timeline("upload", "۶۵٪ رسانه بارگذاری شده است"),
    createdAt: "2026-06-24T09:20:00+03:30",
    updatedAt: "2026-06-25T14:29:00+03:30",
    version: 8,
  },
  {
    id: "job-1002",
    contentId: "content-502",
    title: "گزارش ماهانه عملکرد",
    captionPreview: "مروری بر رشد دسترسی، تعامل و خروجی‌های منتشرشده در ماه جاری.",
    contentType: "link",
    campaign: { id: "campaign-brand", name: "آگاهی از برند" },
    status: "queued",
    progress: 0,
    scheduledAt: "2026-06-25T15:00:00+03:30",
    retryCount: 0,
    maxRetryCount: 3,
    approvalStatus: "approved",
    responsible: users.ali,
    targets: [
      {
        id: "target-1002-linkedin",
        platform: "linkedin",
        accountId: "account-linkedin-company",
        accountName: "Nashrino",
        accountHandle: "nashrino-company",
        status: "queued",
        progress: 0,
      },
    ],
    timeline: timeline("validation", "منتظر آغاز پردازش"),
    createdAt: "2026-06-23T11:00:00+03:30",
    updatedAt: "2026-06-25T12:00:00+03:30",
    version: 3,
  },
  {
    id: "job-1003",
    contentId: "content-503",
    title: "پیشنهاد ویژه پایان هفته",
    captionPreview: "پیشنهاد محدود برای مخاطبان کانال تلگرام با پیوند اختصاصی کمپین.",
    contentType: "image",
    campaign: { id: "campaign-seasonal", name: "فروش پایان فصل" },
    status: "failed",
    progress: 42,
    scheduledAt: "2026-06-25T13:45:00+03:30",
    startedAt: "2026-06-25T13:44:00+03:30",
    delaySeconds: 2700,
    retryCount: 1,
    maxRetryCount: 3,
    approvalStatus: "approved",
    responsible: users.sara,
    latestError: {
      code: "TELEGRAM_MEDIA_REJECTED",
      title: "رسانه توسط مقصد پذیرفته نشد",
      message: "ابعاد تصویر با محدودیت رسانه کانال مقصد سازگار نیست.",
      retryable: true,
      occurredAt: "2026-06-25T13:46:00+03:30",
    },
    targets: [
      {
        id: "target-1003-telegram",
        platform: "telegram",
        accountId: "account-telegram-sales",
        accountName: "فروش نشرینو",
        accountHandle: "@nashrino_sales",
        status: "failed",
        progress: 42,
        latestError: {
          code: "TELEGRAM_MEDIA_REJECTED",
          title: "رسانه توسط مقصد پذیرفته نشد",
          message: "ابعاد تصویر با محدودیت رسانه کانال مقصد سازگار نیست.",
          retryable: true,
          occurredAt: "2026-06-25T13:46:00+03:30",
        },
      },
    ],
    timeline: timeline("upload", "بارگذاری رسانه ناموفق بود", true),
    createdAt: "2026-06-24T16:10:00+03:30",
    updatedAt: "2026-06-25T13:46:00+03:30",
    version: 6,
  },
  {
    id: "job-1004",
    contentId: "content-504",
    title: "پشت صحنه تیم محتوا",
    captionPreview: "روایت کوتاه از فرایند آماده‌سازی تقویم محتوای این هفته.",
    contentType: "video",
    status: "scheduled",
    progress: 0,
    scheduledAt: "2026-06-26T09:00:00+03:30",
    retryCount: 0,
    maxRetryCount: 3,
    approvalStatus: "approved",
    responsible: users.neda,
    targets: [
      {
        id: "target-1004-rubika",
        platform: "rubika",
        accountId: "account-rubika-main",
        accountName: "نشرینو",
        accountHandle: "@nashrino",
        status: "scheduled",
        progress: 0,
      },
    ],
    timeline: timeline("validation", "زمان‌بندی ثبت شده است"),
    createdAt: "2026-06-24T18:20:00+03:30",
    updatedAt: "2026-06-25T10:00:00+03:30",
    version: 2,
  },
  {
    id: "job-1005",
    contentId: "content-505",
    title: "نظرسنجی تجربه کاربران",
    captionPreview: "برای انتخاب قابلیت بعدی محصول، نظر کاربران در چهار پلتفرم دریافت می‌شود.",
    contentType: "image",
    campaign: { id: "campaign-research", name: "صدای مشتری" },
    status: "manual_required",
    progress: 88,
    scheduledAt: "2026-06-25T16:00:00+03:30",
    retryCount: 0,
    maxRetryCount: 1,
    approvalStatus: "approved",
    responsible: users.neda,
    targets: [
      {
        id: "target-1005-instagram",
        platform: "instagram",
        accountId: "account-instagram-personal",
        accountName: "نشرینو استودیو",
        accountHandle: "@nashrino_studio",
        status: "manual_required",
        progress: 88,
      },
    ],
    timeline: timeline("publish_request", "برای تکمیل انتشار، اقدام دستی لازم است"),
    createdAt: "2026-06-24T14:00:00+03:30",
    updatedAt: "2026-06-25T15:50:00+03:30",
    version: 5,
  },
  {
    id: "job-1006",
    contentId: "content-506",
    title: "خبرنامه همکاری جدید",
    captionPreview: "اعلام همکاری جدید و معرفی مسیر مشترک توسعه بازار.",
    contentType: "text",
    status: "paused",
    progress: 14,
    scheduledAt: "2026-06-26T11:30:00+03:30",
    retryCount: 0,
    maxRetryCount: 3,
    approvalStatus: "pending",
    responsible: users.ali,
    targets: [
      {
        id: "target-1006-linkedin",
        platform: "linkedin",
        accountId: "account-linkedin-company",
        accountName: "Nashrino",
        status: "paused",
        progress: 14,
      },
    ],
    timeline: timeline("validation", "تا دریافت تأیید محتوا متوقف شده است"),
    createdAt: "2026-06-25T08:00:00+03:30",
    updatedAt: "2026-06-25T09:30:00+03:30",
    version: 4,
  },
  {
    id: "job-1007",
    contentId: "content-507",
    title: "راهنمای کوتاه برنامه‌ریزی محتوا",
    captionPreview: "سه نکته کوتاه برای ساخت برنامه انتشار منظم و قابل اندازه‌گیری.",
    contentType: "carousel",
    status: "published",
    progress: 100,
    scheduledAt: "2026-06-25T10:00:00+03:30",
    startedAt: "2026-06-25T09:58:00+03:30",
    completedAt: "2026-06-25T10:02:00+03:30",
    retryCount: 0,
    maxRetryCount: 3,
    approvalStatus: "approved",
    responsible: users.sara,
    targets: [
      {
        id: "target-1007-instagram",
        platform: "instagram",
        accountId: "account-instagram-main",
        accountName: "نشرینو",
        accountHandle: "@nashrino_official",
        status: "published",
        progress: 100,
        platformPostId: "ig-507",
        publishedUrl: "https://example.com/posts/ig-507",
      },
      {
        id: "target-1007-telegram",
        platform: "telegram",
        accountId: "account-telegram-main",
        accountName: "نشرینو",
        accountHandle: "@nashrino",
        status: "published",
        progress: 100,
        platformPostId: "tg-507",
        publishedUrl: "https://example.com/posts/tg-507",
      },
    ],
    timeline: timeline("result_recording", "نتیجه انتشار ثبت شد"),
    createdAt: "2026-06-22T12:00:00+03:30",
    updatedAt: "2026-06-25T10:02:00+03:30",
    version: 10,
  },
  {
    id: "job-1008",
    contentId: "content-508",
    title: "یادآوری جلسه آنلاین",
    captionPreview: "یادآوری زمان برگزاری جلسه معرفی قابلیت‌های نسخه جدید.",
    contentType: "story",
    status: "retrying",
    progress: 12,
    scheduledAt: "2026-06-25T14:00:00+03:30",
    startedAt: "2026-06-25T14:05:00+03:30",
    delaySeconds: 900,
    retryCount: 2,
    maxRetryCount: 3,
    approvalStatus: "approved",
    responsible: users.sara,
    targets: [
      {
        id: "target-1008-instagram",
        platform: "instagram",
        accountId: "account-instagram-main",
        accountName: "نشرینو",
        accountHandle: "@nashrino_official",
        status: "retrying",
        progress: 12,
      },
    ],
    timeline: timeline("validation", "تلاش سوم برای انتشار آغاز شده است"),
    createdAt: "2026-06-25T08:40:00+03:30",
    updatedAt: "2026-06-25T14:16:00+03:30",
    version: 7,
  },
];
